package userModules.passwordService;

/**
 * A class to create an object with information about encrypted password.
 * Used to decrypt passwords.
 */
public class EncryptedPassword {
    private final byte[] hashedPassword;
    private final byte[] salt;

    /**
     * A constructor for an object with information about randomly generated byte array (salt) and hashed
     * byte array of salt, password and pepper (hashed password).
     *
     * @param hashedPassword encrypted password. In other words, a hashed byte array of salt, password and pepper
     * @param salt an array of bytes which were randomly generated during password encryption
     */
    public EncryptedPassword(byte[] hashedPassword, byte[] salt) {
        this.hashedPassword = hashedPassword;
        this.salt = salt;
    }

    /**
     * @return encrypted password. In other words, a hashed byte array of salt, password and pepper.
     */
    public byte[] getHashedPassword() {
        return hashedPassword;
    }

    /**
     * @return an array of bytes which were randomly generated during password encryption.
     */
    public byte[] getSalt() {
        return salt;
    }
}