package userModules.passwordService;

import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;

/**
 * An abstraction for every PasswordEncryptor implementation.
 */
public interface PasswordEncryptor {

    /**
     * Encrypts password using some encryption algorithm (depends on the implementation).
     *
     * @param password char array of specified symbols
     * @return an object with information about salt and hashed password
     * @throws NoSuchAlgorithmException thrown when a particular cryptographic algorithm is requested
     * but is not available in the environment
     * @throws NoSuchProviderException thrown when a particular security provider is requested
     * but is not available in the environment
     */
    EncryptedPassword encryptPassword(char[] password) throws NoSuchAlgorithmException, NoSuchProviderException;

    /**
     * @return byte array with generated bytes.
     */
    byte[] generateSalt();

    /**
     * @return byte array with generated symbols.
     */
    byte[] generatePepper();
}